services:
  - type: web
    name: solar-system-management-system
    env: node
    buildCommand: "npm install"
    startCommand: "node server.js"

    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://ssms-websys.netlify.app

      - path: /*
        name: Access-Control-Allow-Methods
        value: GET, POST, PUT, PATCH, DELETE, OPTIONS

      - path: /*
        name: Access-Control-Allow-Headers
        value: Content-Type, Authorization

      - path: /*
        name: Access-Control-Allow-Credentials
        value: "true"