services:
  - type: web
    name: solar-system-management-system
    env: node
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: CORS
        value: "*"
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://ssms-websys.netlify.app
      - path: /*
        name: Access-Control-Allow-Methods
        value: GET, POST, PUT, PATCH, DELETE, OPTIONS
      - path: /*
        name: Access-Control-Allow-Headers
        value: Content-Type, Authorization
